global using Catalog.API.Models;
global using Common.BuildingBlocks.CQRS;
global using Marten;
global using MediatR;
global using Carter;
global using Mapster;
global using FluentValidation;
global using Common.BuildingBlocks.Behaviors;
global using Common.BuildingBlocks.Exceptions.Handler;
